version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: ""
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - .:/var/lib/mysql 

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8000:8080"

  php: 
    image: php
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html/"
    command: php -S 0.0.0.0:9000 -t . 
    working_dir: /var/www/html